#!/bin/tcsh

setenv PROJ UNDEO

setenv IN_PATH /mnt/Education/UNDEO-2017/FieldArchive/

setenv OUT_PATH /mnt/Education/UNDEO-2017/Edits/

setenv CALIB_DATE 20170321
setenv CALIB_FILE calib_0.5us
setenv INDEXED_RES 0.2

foreach iop(20170401-Deployment2)

set iop_file = IOPdir_${RADAR_NAME}/${PROJ}/$iop

# Read lat, lon, alt, heading as env variables

echo sourcing $iop_file
source $iop_file
echo Rotation ${TRUCK_HEADING_DEG}
echo IOP is ${IOP_NAME} and date is ${DATE_STR}

set iqline = ${IN_PATH}${iop}/${RADAR_NAME}/time_series
echo Input path $iqline

../scripts/start_Dsr2Radx.analysis.dow8 $iop_file

echo starting "Iq2Dsr -params Iq2Dsr.analysis.dow8 -f  "
set logfile = "/tmp/Iq2Dsr.analysis.dow8.log"

echo output will be in $logfile
echo Iq2Dsr is running ...........
echo Do not close window ...........
rm -f $logfile

foreach fpath ($iqline/sunscan/dow8 $iqline/save/dow8 $iqline/vert/dow8)
  echo fpath $fpath

  Iq2Dsr -params Iq2Dsr.analysis.UNDEO.dow8 -f  $fpath/*/2*ts >>& $logfile
end

sleep 60

end
