#!/bin/tcsh

setenv PROJ PECAN 

setenv IN_PATH /mnt/PECAN-EditD1/Archive/

setenv OUT_PATH /mnt/PECAN-EditD1/Edits/

setenv CALIB_FILE calib_0.5us
setenv INDEXED_RES 0.5

foreach iop(IOP03 IOP04 IOP10)

set iop_file = IOPdir_${RADAR_NAME}/${PROJ}/$iop

# Read lat, lon, alt, heading as env variables

echo sourcing $iop_file
source $iop_file
echo Rotation ${TRUCK_HEADING_DEG}
echo IOP is ${IOP_NAME} and date is ${DATE_STR}

set iqline = ${IN_PATH}${DATE_STR}/${RADAR_NAME}/time_series
echo Input path $iqline

../scripts/start_Dsr2Radx.analysis.dow8 $iop_file

echo starting "Iq2Dsr -params Iq2Dsr.analysis.dow8 -f  "
set logfile = "/tmp/Iq2Dsr.analysis.dow8.log"

echo output will be in $logfile
echo Iq2Dsr is running ...........
echo Do not close window ...........
rm -f $logfile

foreach fpath ($iqline/save $iqline/vert)
  echo fpath $fpath

  Iq2Dsr -params Iq2Dsr.analysis.dow8-R0 -f  $fpath/20*ts >>& $logfile
end

sleep 60

end
