#!/bin/tcsh

setenv PROJ TWIRL17

setenv IN_PATH /mnt/FBU-A1/FieldArchive/

setenv OUT_PATH /mnt/FBU-A1/Edits/

setenv CALIB_DATE 20170502
setenv CALIB_FILE calib_0.5us
setenv INDEXED_RES 0.25
setenv TRANS_DATE 20170615

foreach iop(20170510-ChildressTX)

set iop_file = IOPdir_${RADAR_NAME}/${PROJ}/$iop
setenv IOP_NAME ${iop}

# Read lat, lon, alt, heading as env variables

echo sourcing $iop_file
source $iop_file
echo "IOP: "${iop}
echo "Rotation Angle: "${TRUCK_HEADING_DEG}
echo "Latitude: "${RADAR_LAT}
echo "Longitude: "${RADAR_LON}
echo "Altitude: "${RADAR_ALT_M}

set iqline = ${IN_PATH}${iop}/${RADAR_NAME}/time_series
echo Input path $iqline

../scripts/start_Dsr2Radx.analysis.dow8 $iop_file

echo starting "Iq2Dsr -params Iq2Dsr.analysis.dow8 -f  "
set logfile = "/tmp/Iq2Dsr.analysis.dow8.log"

echo output will be in $logfile
echo Iq2Dsr is running ...........
echo Do not close window ...........
rm -f $logfile

foreach fpath ($iqline/sunscan/dow8 $iqline/save/dow8 $iqline/vert/dow8)
  echo fpath $fpath

  Iq2Dsr -params Iq2Dsr.analysis.TWIRL17.dow8 -f  $fpath/*/20170510_215*ts >>& $logfile
end

end
