#! /bin/csh -f

#
# clean data for a specified day from the raid
#

set daydir = $1

cd 
cd projDir/data

ls */*/*/${daydir}*
echo "========================================================="
echo "WARNING: you are about to remove data for day: $daydir"
echo "========================================================="
echo -n "WARNING: do you wish to proceed? (y/n): "
if ("$<" != "y") then
    echo "Aborted"
    exit 1
endif
echo "Proceeding ......."

foreach dir ( \
 dorade/moments/high/${daydir} \
 dorade/moments/low/${daydir} \
 dorade/moments/combined/${daydir} \
 cfradial/moments/high/${daydir} \
 cfradial/moments/low/${daydir} \
 cfradial/moments/combined/${daydir} \
 time_series/save/high/${daydir} \
 time_series/save/low/${daydir} \
)

  echo "  cleaning dir: $dir"
  /bin/rm -rf $dir

end
