//#ifndef _HIQ_HARDWARE_H_
//#define _HIQ_HARDWARE_H_
#pragma once

/************************************************************************
*  File: hiq_lib.h
*
*  Library for accessing HIQ devices using a Kernel PlugIn driver.
*  The code accesses hardware using WinDriver's WDC library.
*  Code was generated by DriverWizard v9.20.
*
*  Jungo Confidential. Copyright (c) 2009 Jungo Ltd.  http://www.jungo.com
*************************************************************************/

#include "wdc_lib.h"
#include "pci_regs.h"
#include "bits.h"

#ifdef __cplusplus
extern "C" {
#endif

/*************************************************************
  General definitions
 *************************************************************/
/* the bits of the 16 bit Status register */
/* WRITE: -STATUS_WR on U12 */
/* READ : -STATUS_RD on U13 */
#define	STAT_TRESET		0x0001
#define STAT_TMODE		0x0002	// trigger mode
#define STAT_SPARE0		0x0004	// spare
#define STAT_DSIGN		0x0008
#define STAT_TRIGE		0x0010
#define STAT_TRIGO		0x0020
#define STAT_SWSEL		0x0040
#define STAT_SWCTRL		0x0080
#define STAT_GATE0		0x0100	// gate0 mode, phase correct
#define STAT_SPARE1		0x0200	// spare
#define STAT_SPARE2		0x0400	// spare
#define STAT_TRIGSEL	0x0800	// trigger select
#define STAT_WATCHDOG	0x1000	// watchdog LED
#define STAT_PLLCLK		0x2000	// phase lock loop clock
#define STAT_PLLLE		0x4000	// phase lock loop SOMETHING
#define STAT_PLLDATA	0x8000	// phase lock loop data
#define STAT_LED		STAT_WATCHDOG	// one of 4 LEDs

/* the bits of the 8 bit Status1 register */
/* READ: -STATUS1_RD on U16 */
#define STAT_FIRST		0x0001	// FIRST_TRIG
#define STAT_PLOCK		0x0002	// phase locked, -PHASELOCK, +PHASEALARM
					//	0x0004	// 0, Grounded input on U16
					//	0x0008	// 0, Grounded input on U16
#define STAT_FIFOHF		0x0010	// fifo half full
#define STAT_FIFOFF		0x0020	// fifo full
#define STAT_FIFOEF		0x0040	// fifo empty
					//	0x0080	// 0, Grounded input on U16

// Active bits in the Interrupt Control/Status register (in U18, PC_IF design file).
#define INT_EOF			0x0001	// mask / enable the End of File interrupt, bit D0.
#define INT_FIFO_HF		0x0002	// mask / enable the HF interrupt, bit D1.

#define INT_FISTTRIG	0x0004

/*************************************************************
  Function prototypes
 *************************************************************/
// Function: HIQ_func()


#ifdef __cplusplus
}
#endif

//#endif
