#! /bin/bash

#--------------------------------------------------------------------
#
# script to configure a host for the DOW TITAN data system
#
# Mike Dixon, EOL, NCAR, Boulder, CO, USA
# May 2013
#
#--------------------------------------------------------------------
#
# Makes links to the proc_list, data_list and crontab files
#
#--------------------------------------------------------------------

# set the path

export PATH=.:/bin:/usr/bin:/sbin:/usr/sbin:/usr/bin/X11:/usr/local/bin:/usr/local/sbin

#--------------------------------------------------------------------
# usage function
#

function usage() {
    echo
    echo "Usage: configure_host [ -d -h -v ] -r root_dir -D data_dir"
    echo
    echo "  -h:  produce this usage list"
    echo "  -d:  turn debugging on"
    echo "  -v:  version"
    echo "  -r:  specify root directory (required arg)"
    echo "       This dir contains projects, apps and libs"
    echo "  -D:  specify data dir"
    echo "       i.e. the top dir for the data"
    echo
}

#--------------------------------------------------------------------
# check args

DATA_DIR="/data/dow"
ROOT_DIR="$HOME/cvs"
debug=false

# Parse command line options.
while getopts hvdr:D: OPT; do
    case "$OPT" in
        h)
            usage
            exit 0
            ;;
        d)
            debug=true
            ;;
        v)
            echo "`basename $0` version 1.0"
            exit 0
            ;;
        r)
            ROOT_DIR=$OPTARG
            ;;
        D)
            DATA_DIR=$OPTARG
            ;;
        \?)
            # getopts issues an error message
            echo "Problems with command line usage"
            usage
            exit 1
            ;;
    esac
done

# Remove the switches we parsed above.
shift `expr $OPTIND - 1`

if [ "$ROOT_DIR" == "not_set" ] 
then
    echo
    echo "ERROR - bad command line"
    echo "  Must specify root dir using -r option"
    usage
    exit -1
fi

if [ "$debug" == "true" ]
then
    set -x
    echo "ROOT_DIR is $ROOT_DIR"
    echo "DATA_DIR is $DATA_DIR"
    echo "debug is $debug"
fi

# set directory paths

cvs_dow_dir=$ROOT_DIR/projects/titan/dow
cvs_proj_dir=$cvs_dow_dir/dualFreq
system_dir=$cvs_proj_dir/system

echo "cvs_dow_dir: $cvs_dow_dir"
echo "cvs_proj_dir: $cvs_proj_dir"
echo "system_dir: $system_dir"

#-- get current host type if possible -------------------------------
#
# This is stored in the file ~/.host_type

installed_host_type=mgen
if [ -e $HOME/.host_type ]
then
  installed_host_type=`cat $HOME/.host_type`
  echo "  Found installed host type: '$installed_host_type'"
  echo
fi

#-- get host type ---------------------------------------------------

while [ "$host_type" != mgen6 -a \
        "$host_type" != mgen7 -a \
        "$host_type" != mgen8 -a \
        "$host_type" != mgenr -a \
        "$host_type" != drx6 -a \
        "$host_type" != drx7 -a \
        "$host_type" != drx8 -a \
        "$host_type" != drxr ]

do

echo "Choose host type from the following list"
echo " or hit enter to use existing host type as shown:"
echo
echo "    mgen6"
echo "    mgen7"
echo "    mgen8"
echo "    mgenr"
echo "    drx6"
echo "    drx7"
echo "    drx8"
echo "    drxr"
read -ep "    ......($installed_host_type)? " host_type
test "$host_type" || host_type=$installed_host_type
echo

if [ "$host_type" != mgen6 -a \
     "$host_type" != mgen7 -a \
     "$host_type" != mgen8 -a \
     "$host_type" != mgenr -a \
     "$host_type" != drx6 -a \
     "$host_type" != drx7 -a \
     "$host_type" != drx8 -a \
     "$host_type" != drxr ]

then

    echo -n X | tr X '\07'	# Beep.
    echo
    echo "  ERROR - invalid host type ..."
    echo "          try again ..."

fi

done

# set radar name

if [ "$host_type" = 'drx6' ];
then
    radar_name=dow6
elif [ "$host_type" = 'mgen6' ];
then
    radar_name=dow6
elif [ "$host_type" = 'drx7' ];
then
    radar_name=dow7
elif [ "$host_type" = 'mgen7' ];
then
    radar_name=dow7
elif [ "$host_type" = 'drx8' ];
then
    radar_name=dow8
elif [ "$host_type" = 'mgen8' ];
then
    radar_name=dow8
elif [ "$host_type" = 'drxr' ];
then
    radar_name=dowr
elif [ "$host_type" = 'mgenr' ];
then
    radar_name=dowr
fi

# save the host type

echo $host_type > $HOME/.host_type

echo
echo "*********************************************************************"
echo
echo "  configure_host for $radar_name"
echo
echo "  `date`"
echo
echo "  host type: $host_type"
echo
echo "*********************************************************************"
echo

# create directory for backup links

backup_links_dir=$HOME/.backup_links
/bin/rm -rf $backup_links_dir
mkdir -p $backup_links_dir || exit 1

# make links to dotfiles in cvs

cd $HOME
for dotfile in cshrc bashrc emacs cvsignore Xdefaults
do
    echo "/bin/mv -f .$dotfile $backup_links_dir"
    /bin/mv -f .$dotfile $backup_links_dir
    ln -s $system_dir/dotfiles/$dotfile .$dotfile || exit 1
done

# make link to projDir

cd $HOME
echo "/bin/mv -f projDir $backup_links_dir || exit 1"
/bin/mv -f projDir $backup_links_dir
echo "ln -s $cvs_proj_dir projDir || exit 1"
ln -s $cvs_proj_dir projDir || exit 1

############################################
# data dir - specific to the host type
# copy data dir into /data/dow,
#   which must be writable by dow
# make link to data dir

cvs_data_dir=$cvs_dow_dir/data_dirs/data.${host_type}
inst_data_dir=$DATA_DIR/data.${host_type}

cd $HOME/projDir || exit 1
mkdir -p $DATA_DIR || exit 1
rsync -av $cvs_data_dir $DATA_DIR || exit 1
/bin/mv -f data $backup_links_dir
ln -s $inst_data_dir data || exit 1

# log dir

/bin/mv -f logs $backup_links_dir
ln -s data/logs || exit 1

#####################
# set up control dir

cd $HOME/projDir/control || exit 1

# make backups as required

/bin/mv -f crontab $backup_links_dir
/bin/mv -f proc_list $backup_links_dir
/bin/mv -f data_list $backup_links_dir

# set links based on host type

ln -s proc_list.$host_type proc_list || exit 1
ln -s data_list.$host_type data_list || exit 1
ln -s crontab.$host_type crontab || exit 1

#####################################
# link radar info based on host type

cd $HOME/projDir/system/params || exit 1
/bin/rm radar_info
ln -s radar_info.$radar_name radar_info || exit 1


