#! /usr/bin/perl
#
# get_host_type
#
# Purpose: print the host type by interpreting the host name.
#-------------------------------------------------------------------

use Env;
Env::import();

# initialize main variables

$hostname = $ENV{'HOST'};

if ($hostname =~ /mgen/) {
    print "mgen\n";
} elsif ($hostname =~ /pgen/) {
    print "pgen\n";
} elsif ($hostname =~ /drx/) {
    print "drx\n";
} else {
    print "mgen\n";
}
