#! /bin/bash

#--------------------------------------------------------------------
#
# back up files to clone system
#
# run as root
#
# Usage: clone_backup tar_file_name
#
#--------------------------------------------------------------------

# back up from root

cd /

# set the path

export PATH=.:/bin:/usr/bin:/sbin:/usr/sbin:/usr/bin/X11:/usr/local/bin:/usr/local/sbin

# set dest dir

tar_name=$1

# make sure data dir exists

if [ ! -e data ]; then
  mkdir data
fi

# tar up

tar cvf $tar_name bin data etc home lib lib64 opt sbin selinux usr

