#! /bin/bash

# wrapper around stop_all to query the user

echo
echo -n X | tr X '\07'	# Beep.
read -ep "Are you sure you want to stop the system? [yes/no]? " answer
test "$answer" || answer=no

if [ "$answer" != yes -a \
     "$answer" != y ]
then
    echo -n X | tr X '\07'	# Beep.
    echo
    echo "  CANCELLING SHUTDOWN"
    echo
    sleep 5
    exit 0
fi

echo -n X | tr X '\07'	# Beep.
echo
echo "  STARTING SHUTDOWN" 
echo

~/projDir/system/scripts/stop_all
